'use client';

import {
  Database,
  Sparkles,
  HardDrive,
  ShieldCheck,
  Github,
  type LucideIcon,
} from 'lucide-react';
import { Modal } from './Modal';

function Section({
  Icon,
  title,
  children,
}: {
  Icon: LucideIcon;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="border-t border-sage/40 pt-4 first:border-t-0 first:pt-0">
      <div className="flex items-center gap-2">
        <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg border border-sage/60 bg-mint/40 text-bottle">
          <Icon className="h-4 w-4" aria-hidden="true" />
        </span>
        <h3 className="font-display text-base font-semibold text-bottle">{title}</h3>
      </div>
      <div className="mt-2 space-y-2 text-sm leading-relaxed text-ink/75">
        {children}
      </div>
    </section>
  );
}

export function PrivacyModal({
  open,
  onClose,
}: {
  open: boolean;
  onClose: () => void;
}) {
  return (
    <Modal open={open} onClose={onClose} title="Privacy" maxWidthClass="max-w-xl">
      <p className="mb-5 text-sm leading-relaxed text-ink/70">
        AuditIQ is an anonymous AI cost-optimization tool. There are no accounts,
        no logins, no passwords, and no payment processing — so we collect as
        little as possible to run your audit.
      </p>

      <div className="space-y-5">
        <Section Icon={Database} title="Information collected">
          <p>When you run an audit, we process the inputs you provide:</p>
          <ul className="list-disc space-y-1 pl-5 marker:text-sap">
            <li>Team size</li>
            <li>Tool selections</li>
            <li>Plan selections</li>
            <li>Seat counts and monthly cost information</li>
          </ul>
          <p>
            We do not ask for your name, email, or company to generate an audit.
            We do not build advertising or personal profiles.
          </p>
        </Section>

        <Section Icon={Sparkles} title="AI processing">
          <p>
            Your audit summary is generated by Google Gemini using only the audit
            figures above. If the AI service is unavailable, AuditIQ falls back to
            a deterministic summary generated locally on our server — your audit
            still completes either way.
          </p>
        </Section>

        <Section Icon={HardDrive} title="Storage">
          <p>
            Your audit inputs and the generated summary are saved in our database
            so your results can be viewed and shared. Each audit is identified
            only by a random, unguessable share link — never by your identity.
            No names, emails, or company details are stored in the audit record.
          </p>
          <p>
            While you fill out the form, a draft is saved in your browser&apos;s
            <span className="font-mono text-xs"> localStorage</span> (key{' '}
            <span className="font-mono text-xs">auditiq_form_state</span>) so you
            don&apos;t lose progress. It stays on your device and is cleared once
            your audit is submitted. AuditIQ does not set advertising or analytics
            cookies.
          </p>
        </Section>

        <Section Icon={ShieldCheck} title="Security">
          <p>Safeguards currently in place:</p>
          <ul className="list-disc space-y-1 pl-5 marker:text-sap">
            <li>HTTPS/TLS encryption in transit and AES-256 encryption at rest.</li>
            <li>Strict server-side validation (Zod) on every submission.</li>
            <li>Rate limiting and a bot honeypot to prevent abuse.</li>
            <li>
              Hardened HTTP headers: HSTS, <span className="font-mono text-xs">X-Frame-Options:
              DENY</span>, <span className="font-mono text-xs">X-Content-Type-Options:
              nosniff</span>, a strict Referrer-Policy and Permissions-Policy.
            </li>
            <li>
              No accounts, passwords, or card data — eliminating entire classes of
              credential and payment risk.
            </li>
          </ul>
        </Section>

        <Section Icon={Github} title="Contact">
          <p>
            AuditIQ is currently an independent portfolio project and does not
            maintain a dedicated support mailbox.
          </p>
          <p>
            For questions, feedback, or bug reports, please use the project&apos;s
            GitHub repository.
          </p>
        </Section>
      </div>
    </Modal>
  );
}
