import { AI_CONFIG } from './config';
import { GeminiProvider } from './providers/gemini';
import { SYSTEM_PROMPT_AUDIT_SUMMARY } from './prompts/system';
import { buildAuditSummaryPrompt } from './prompts/audit-summary';
import { aiSummaryResponseSchema } from './schemas/summary';
import { withRetry } from './utils/retry';
import { sanitizeOutput } from './utils/sanitize';
import { serializeAISummary, generateFallbackSummary } from './serializers';
import { aiSummaryService } from '../services/ai-summary.service';
import { logger } from '../logger';
import { AuditSelect } from '../repositories/audit';
import { ToolAuditFindings } from '../audit/types';

// We abstract the provider instantiation here to easily swap it later.
const provider = new GeminiProvider(AI_CONFIG);

/**
 * Main orchestration function for generating an AI summary of an audit.
 * Enforces structured JSON output, handles timeouts, retries, and fallbacks.
 * 
 * @param audit The database audit record.
 * @param findings The deterministic findings generated by the audit engine.
 * @returns A strictly formatted string summary.
 */
export async function generateAuditSummary(
  audit: AuditSelect, 
  findings: ToolAuditFindings[]
): Promise<string> {
  const startTime = Date.now();

  // Deterministic context shared by both the prompt and the fallback.
  const context = aiSummaryService.prepareSummaryContext(audit, findings);

  try {
    logger.info(
      { auditId: audit.id, model: AI_CONFIG.model },
      'Starting AI summary generation'
    );

    const userPrompt = buildAuditSummaryPrompt(context);

    // Execute provider with retry wrapper and timeout handling
    const rawResponse = await withRetry(
      () => provider.generateSummary(userPrompt, SYSTEM_PROMPT_AUDIT_SUMMARY),
      AI_CONFIG.maxRetries,
      AI_CONFIG.timeoutMs,
      'generate_audit_summary'
    );

    // Sanitize any potential markdown leaks (e.g. ```json ... ```)
    const sanitizedString = sanitizeOutput(rawResponse);
    
    // Parse to structured JSON object safely
    const parsedJson = JSON.parse(sanitizedString);
    
    // Validate output matches exact expected Zod schema
    const validatedData = aiSummaryResponseSchema.parse(parsedJson);
    
    // Serialize to frontend-safe string
    const finalSummary = serializeAISummary(validatedData);

    const latencyMs = Date.now() - startTime;
    logger.info(
      { auditId: audit.id, latencyMs, model: AI_CONFIG.model },
      'Successfully generated AI summary'
    );

    return finalSummary;

  } catch (error) {
    const latencyMs = Date.now() - startTime;
    const reason = error instanceof Error ? error.message : 'Unknown error';

    logger.error(
      { auditId: audit.id, latencyMs, model: AI_CONFIG.model, reason },
      'AI summary generation failed. Returning deterministic fallback.'
    );

    return generateFallbackSummary(context);
  }
}
